import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const config=window.STORE_CONFIG||{},supabase=createClient(config.SUPABASE_URL,config.SUPABASE_PUBLISHABLE_KEY),$=s=>document.querySelector(s);let products=[];
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const{data:{session}}=await supabase.auth.getSession();
if(!session)location.replace("auth.html");else{const{data:profile}=await supabase.from("profiles").select("role").eq("id",session.user.id).single();if(profile?.role!=="admin")location.replace("index.html");else{$("#loading").hidden=true;$("#app").hidden=false;await loadDashboard()}}
async function loadDashboard(){const[productResult,orderResult,subscriberResult]=await Promise.all([supabase.from("products").select("*").order("sort_order"),supabase.from("orders").select("id,customer_name,customer_email,status,amount_total_cents,created_at").order("created_at",{ascending:false}).limit(25),supabase.from("newsletter_subscribers").select("id",{count:"exact",head:true})]);products=productResult.data||[];$("#product-count").textContent=products.length;$("#order-count").textContent=orderResult.data?.length||0;$("#subscriber-count").textContent=subscriberResult.count||0;$("#products").innerHTML='<table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th></th></tr></thead><tbody>'+products.map(item=>`<tr><td><strong>${escapeHtml(item.name)}</strong></td><td>${escapeHtml(item.category)}</td><td>$${(item.price_cents/100).toFixed(2)}</td><td>${item.inventory??"Unlimited"}</td><td>${item.active?"Active":"Hidden"}</td><td class="table-actions"><button class="ghost edit" data-id="${item.id}">Edit</button><button class="ghost delete" data-id="${item.id}">Delete</button></td></tr>`).join("")+"</tbody></table>";$("#orders").innerHTML=orderResult.data?.length?'<table><thead><tr><th>Date</th><th>Customer</th><th>Email</th><th>Status</th><th>Total</th></tr></thead><tbody>'+orderResult.data.map(item=>`<tr><td>${new Date(item.created_at).toLocaleDateString()}</td><td>${escapeHtml(item.customer_name||"—")}</td><td>${escapeHtml(item.customer_email||"—")}</td><td>${escapeHtml(item.status)}</td><td>$${(item.amount_total_cents/100).toFixed(2)}</td></tr>`).join("")+"</tbody></table>":"No orders yet.";document.querySelectorAll(".edit").forEach(button=>button.onclick=()=>openEditor(products.find(item=>item.id===button.dataset.id)));document.querySelectorAll(".delete").forEach(button=>button.onclick=()=>deleteProduct(button.dataset.id))}
function openEditor(product={}){$("#product-form").reset();$("#product-id").value=product.id||"";$("#product-name").value=product.name||"";$("#slug").value=product.slug||"";$("#category").value=product.category||"candles";$("#price").value=product.price_cents!=null?(product.price_cents/100).toFixed(2):"";$("#inventory").value=product.inventory??"";$("#sort").value=product.sort_order||0;$("#badge").value=product.badge||"";$("#visual").value=product.visual||"✦";$("#color").value=product.color||"#efe4d4";$("#active").value=String(product.active??true);$("#description").value=product.description||"";$("#form-title").textContent=product.id?"Edit product":"Add product";$("#notice").textContent="";$("#editor").showModal()}
async function deleteProduct(id){if(!confirm("Delete this product?"))return;const{error}=await supabase.from("products").delete().eq("id",id);if(error)alert(error.message);else await loadDashboard()}
$("#product-form").onsubmit=async event=>{event.preventDefault();const id=$("#product-id").value,row={name:$("#product-name").value.trim(),slug:$("#slug").value.trim().toLowerCase(),category:$("#category").value,price_cents:Math.round(Number($("#price").value)*100),inventory:$("#inventory").value===""?null:Number($("#inventory").value),sort_order:Number($("#sort").value),badge:$("#badge").value.trim(),visual:$("#visual").value.trim()||"✦",color:$("#color").value,active:$("#active").value==="true",description:$("#description").value.trim()};const{error}=id?await supabase.from("products").update(row).eq("id",id):await supabase.from("products").insert(row);if(error)$("#notice").textContent=error.message;else{$("#editor").close();await loadDashboard()}};
$("#add").onclick=()=>openEditor();$("#cancel").onclick=()=>$("#editor").close();$("#signout").onclick=async()=>{await supabase.auth.signOut();location.replace("auth.html")};
